package dev.hadamard.companion.agent

import org.json.JSONObject

/**
 * Parses the static provider-export QR payload generated by the desktop GUI
 * ("Share a provider with your phone" in the Devices tab). The QR code encodes
 * the provider configuration directly — no network handshake is involved.
 */
object ProviderQrPayload {
  const val TYPE = "hadamard-provider"

  data class Parsed(
    val displayName: String,
    val endpoint: String,
    val model: String,
    val apiKey: String,
  )

  fun parse(contents: String): Parsed {
    val json = JSONObject(contents)
    require(json.optString("type") == TYPE) { "Unexpected QR payload type" }
    val endpoint = json.optString("endpoint").trim()
    val model = json.optString("model").trim()
    val apiKey = json.optString("apiKey").trim()
    require(endpoint.isNotEmpty() && model.isNotEmpty() && apiKey.isNotEmpty()) {
      "Provider QR payload is incomplete"
    }
    return Parsed(
      displayName = json.optString("displayName").trim(),
      endpoint = endpoint,
      model = model,
      apiKey = apiKey,
    )
  }
}
